# Generated by Django 5.0.3 on 2024-04-23 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('neighbor_id', models.IntegerField()),
                ('event_description', models.CharField(max_length=1000)),
                ('event_name', models.CharField(max_length=50)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('event_reoccur', models.CharField(max_length=14)),
                ('event_address', models.CharField(max_length=50)),
                ('event_city', models.CharField(max_length=100)),
                ('event_state', models.CharField(max_length=15)),
                ('event_zipcode', models.CharField(max_length=10)),
                ('event_public', models.BooleanField()),
                ('event_invitees', models.TextField()),
                ('evented_when', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('login_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('neighbor_id', models.IntegerField()),
                ('login_datetime', models.DateTimeField()),
                ('login_ip', models.GenericIPAddressField()),
                ('login_rememberme', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbors',
            fields=[
                ('neighbor_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('signup_datetime', models.DateTimeField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=35)),
                ('zipcode', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)])),
                ('verfication_code', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signouts',
            fields=[
                ('signout_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('neighbor_id', models.IntegerField()),
                ('signout_when', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Verification_skips',
            fields=[
                ('skip_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('neighbor_id', models.IntegerField()),
                ('skipped_when', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Verify_laters',
            fields=[
                ('verify_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('neighbor_id', models.IntegerField()),
                ('clicked_when', models.DateTimeField()),
            ],
        ),
    ]
