# Generated by Django 5.0.3 on 2024-04-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_verfication_code_neighbors_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verify_laters',
            old_name='verify_id',
            new_name='later_id',
        ),
        migrations.RenameField(
            model_name='verify_laters',
            old_name='clicked_when',
            new_name='later_when',
        ),
    ]
