# Generated by Django 5.0.3 on 2024-04-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_verifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbors',
            name='friends',
            field=models.CharField(default='none'),
        ),
    ]
