# Generated by Django 5.0.3 on 2024-04-24 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_neighbors_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='neighbor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors'),
        ),
        migrations.AlterField(
            model_name='logins',
            name='neighbor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors'),
        ),
        migrations.AlterField(
            model_name='signouts',
            name='neighbor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors'),
        ),
        migrations.AlterField(
            model_name='verification_skips',
            name='neighbor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors'),
        ),
        migrations.AlterField(
            model_name='verifiers',
            name='neighbor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors'),
        ),
        migrations.AlterField(
            model_name='verify_laters',
            name='neighbor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors'),
        ),
    ]
