# Generated by Django 5.0.3 on 2024-04-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_events_neighbor_id_alter_logins_neighbor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='neighbor_id',
            new_name='neighbor',
        ),
        migrations.RenameField(
            model_name='logins',
            old_name='neighbor_id',
            new_name='neighbor',
        ),
        migrations.RenameField(
            model_name='signouts',
            old_name='neighbor_id',
            new_name='neighbor',
        ),
        migrations.RenameField(
            model_name='verification_skips',
            old_name='neighbor_id',
            new_name='neighbor',
        ),
        migrations.RenameField(
            model_name='verifiers',
            old_name='neighbor_id',
            new_name='neighbor',
        ),
        migrations.RenameField(
            model_name='verify_laters',
            old_name='neighbor_id',
            new_name='neighbor',
        ),
    ]
