# Generated by Django 4.2.6 on 2024-04-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_neighbor_id_events_neighbor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbors',
            name='profile_picture',
            field=models.CharField(default='none'),
        ),
        migrations.AlterField(
            model_name='neighbors',
            name='address',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='neighbors',
            name='zipcode',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
