# Generated by Django 5.0.3 on 2024-04-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_neighbors_profile_picture_alter_neighbors_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_checks',
            fields=[
                ('friend_check_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('friend_check_when', models.DateTimeField()),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors')),
            ],
        ),
    ]
