# Generated by Django 5.0.3 on 2024-05-02 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_friend_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbors',
            name='password',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
