# Generated by Django 5.0.3 on 2024-05-04 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_neighbors_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_filters',
            fields=[
                ('location_filter_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('location_filter', models.CharField(max_length=15)),
                ('location_filtered_when', models.DateTimeField()),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors')),
            ],
        ),
    ]
