# Generated by Django 5.0.3 on 2024-05-05 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_location_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_filters',
            fields=[
                ('view_filter_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('view_filter', models.CharField(max_length=13)),
                ('view_filtered_when', models.DateTimeField()),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors')),
            ],
        ),
    ]
