# Generated by Django 5.0.3 on 2024-05-05 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_view_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_filters',
            fields=[
                ('calendar_filter_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('calendar_filtered_when', models.DateTimeField()),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors')),
            ],
        ),
    ]
