# Generated by Django 5.0.3 on 2024-05-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_date_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbors',
            name='username',
            field=models.CharField(default='youyoungjune', max_length=255),
            preserve_default=False,
        ),
    ]
