# Generated by Django 5.0.3 on 2024-05-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_neighbors_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logins',
            name='login_rememberme',
        ),
        migrations.AlterField(
            model_name='neighbors',
            name='first_name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='neighbors',
            name='last_name',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
