# Generated by Django 5.0.3 on 2024-05-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_logins_login_rememberme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_zipcode',
            field=models.CharField(max_length=17),
        ),
    ]
