# Generated by Django 5.0.3 on 2024-05-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_event_views_home_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('visit_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('visit_ip', models.GenericIPAddressField()),
                ('visited_when', models.DateTimeField()),
            ],
        ),
    ]
