# Generated by Django 5.0.3 on 2024-05-18 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_views',
            fields=[
                ('friend_view_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('friend_id', models.IntegerField()),
                ('friend_viewed_when', models.DateTimeField()),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighbors')),
            ],
        ),
    ]
