# Generated by Django 5.0.3 on 2024-05-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_addresses_id_addresses_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='state',
        ),
        migrations.AddField(
            model_name='neighbors',
            name='city',
            field=models.CharField(default='Syracuse', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbors',
            name='state',
            field=models.CharField(default='New York', max_length=35),
            preserve_default=False,
        ),
    ]
