# Generated by Django 5.0.3 on 2024-05-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_addresses_city_remove_addresses_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_private',
            field=models.BooleanField(default=False),
        ),
    ]
