# Generated by Django 4.2.6 on 2024-05-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_events_event_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='neighbors',
            name='city',
        ),
        migrations.RemoveField(
            model_name='neighbors',
            name='state',
        ),
        migrations.AddField(
            model_name='addresses',
            name='city',
            field=models.CharField(default='Syracuse', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='state',
            field=models.CharField(default='New York', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbors',
            name='zipcode',
            field=models.CharField(default='none', max_length=17),
        ),
    ]
