# Generated by Django 4.2.6 on 2024-05-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_addresses_zipcode_remove_neighbors_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='neighbors',
            name='zipcode',
            field=models.CharField(default='Your zipcode here', max_length=17),
        ),
    ]
