# Generated by Django 4.2.6 on 2024-05-26 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_addresses_address_alter_addresses_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('neighborhood_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('neighborhood', models.CharField(default='Not assigned', max_length=255)),
                ('neighborhood_found_when', models.DateTimeField(default=datetime.datetime(2024, 5, 25, 20, 21, 39, 86256))),
            ],
        ),
    ]
