# Generated by Django 4.2.6 on 2024-05-26 00:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_neighborhoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='neighborhood',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.neighborhoods'),
        ),
        migrations.AddField(
            model_name='events',
            name='neighborhood',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.neighborhoods'),
        ),
        migrations.AddField(
            model_name='neighbors',
            name='neighborhood',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.neighborhoods'),
        ),
        migrations.AlterField(
            model_name='neighborhoods',
            name='neighborhood_found_when',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 20, 24, 49, 356133)),
        ),
    ]
