# Generated by Django 4.2.6 on 2024-05-26 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_addresses_neighborhood_events_neighborhood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcodes',
            fields=[
                ('zipcode_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=27)),
                ('state', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_city',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_state',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='neighborhoods',
            name='neighborhood_found_when',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 21, 48, 37, 748032)),
        ),
    ]
