# Generated by Django 4.2.6 on 2024-05-26 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_neighborhoods_neighborhood_found_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoods',
            name='neighborhood_found_when',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 21, 52, 5, 796154)),
        ),
    ]
